import { Teacher } from "@/types/teacher";

const teachersData: Teacher[] = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    designation: "Computer Science Professor",
    image: "/images/teachers/teacher-1.jpeg",
    bio: "Ph.D. in Computer Science with 10+ years of teaching experience in algorithms and data structures.",
    email: "sarah.j@example.com",
    linkedin: "linkedin.com/in/sarahj",
    twitter: "@sarahj",
  },
  {
    id: 2,
    name: "Prof. Michael Chen",
    designation: "Mathematics Department Head",
    image: "/images/teachers/teacher-2.jpg",
    bio: "Specialized in advanced calculus and mathematical modeling with numerous published research papers.",
    email: "m.chen@example.com",
    linkedin: "linkedin.com/in/michaelc",
    twitter: "@profchen",
  },
  {
    id: 3,
    name: "Dr. Emily Brown",
    designation: "Physics Instructor",
    image: "/images/teachers/teacher-3.jpg",
    bio: "Research focus on quantum mechanics and particle physics. Lead researcher on multiple NSF grants.",
    email: "e.brown@example.com",
    linkedin: "linkedin.com/in/emilyb",
    twitter: "@drebrown",
  },
  {
    id: 4,
    name: "Dr. Liam Walker",
    designation: "Artificial Intelligence Expert",
    image: "/images/teachers/teacher-4.webp",
    bio: "AI researcher with a strong background in neural networks and natural language processing.",
    email: "liam.w@example.com",
    linkedin: "linkedin.com/in/liamw",
    twitter: "@liamwalker",
  },
  {
    id: 5,
    name: "Prof. Olivia Davis",
    designation: "Biology Lecturer",
    image: "/images/teachers/teacher-5.jpg",
    bio: "Specialist in molecular biology and genetics with over a decade of teaching experience.",
    email: "olivia.d@example.com",
    linkedin: "linkedin.com/in/oliviad",
    twitter: "@prof_olivia",
  },
  {
    id: 6,
    name: "Dr. Ethan Martinez",
    designation: "Chemistry Researcher",
    image: "/images/teachers/teacher-6.jpg",
    bio: "Focused on organic chemistry and sustainable material science. Author of 20+ scientific papers.",
    email: "ethan.m@example.com",
    linkedin: "linkedin.com/in/ethanm",
    twitter: "@dr_ethan",
  },
  {
    id: 7,
    name: "Dr. Ava Thompson",
    designation: "History Professor",
    image: "/images/teachers/teacher-7.jpg",
    bio: "Historian specializing in ancient civilizations and modern history methodologies.",
    email: "ava.t@example.com",
    linkedin: "linkedin.com/in/avathompson",
    twitter: "@profava",
  },
  {
    id: 8,
    name: "Prof. William Garcia",
    designation: "Engineering Faculty",
    image: "/images/teachers/teacher-8.jpg",
    bio: "Mechanical engineer with expertise in robotics and automation. Mentor to multiple engineering teams.",
    email: "william.g@example.com",
    linkedin: "linkedin.com/in/williamg",
    twitter: "@eng_garcia",
  },
  {
    id: 9,
    name: "Dr. Mia Wilson",
    designation: "Psychology Instructor",
    image: "/images/teachers/teacher-9.jpg",
    bio: "Clinical psychologist with a research focus on behavioral therapy and cognitive science.",
    email: "mia.w@example.com",
    linkedin: "linkedin.com/in/miawilson",
    twitter: "@psychmia",
  },
  {
    id: 10,
    name: "Dr. Lucas Anderson",
    designation: "Environmental Science Specialist",
    image: "/images/teachers/teacher-10.jpg",
    bio: "Environmental scientist focusing on climate change and renewable energy solutions.",
    email: "lucas.a@example.com",
    linkedin: "linkedin.com/in/lucasa",
    twitter: "@dr_lucas",
  },
];

export default teachersData;
